SocialTodoList/core/urls.py
from django.conf.urls import url

from . import views

app_name = "core"
handler404 = 'SocialTodoList.core.views.show_lists'

urlpatterns = [
    url(r'^lists/$', views.react_index, name="react_index"),
    url(r'^get_all_lists/$', views.get_all_lists, name="get_all_lists"),
    url(r'^create_list/$', views.create_new_list, name='create_list'),
    url(r'^delete_list/(?P<list_id>\d+)/$', views.delete_list, name='delete_list'),
    url(r'^get_list_info/(?P<list_id>\d+)/$', views.get_list_info, name='get_list_info'),
    url(r'^edit_list/(?P<list_id>\d+)/add_item/$', views.add_item_to_list, name='add_item_to_list'),
    url(r'^edit_list/(?P<list_id>\d+)/delete_item/(?P<item_id>\d+)/$', views.delete_item_from_list, name='delete_item_from_list'),
    url(r'^edit_list/(?P<list_id>\d+)/toggle_done/(?P<item_id>\d+)/$', views.toggle_item_done_from_list, name='toggle_item_done'),
    url(r'^get_item_info/(?P<item_id>\d+)/$', views.get_item_info, name='get_item_info'),
    url(r'^edit_list/(?P<list_id>\d+)/edit_item/(?P<item_id>\d+)/edit/$', views.edit_item_from_list, name='edit_item'),
    url(r'^edit_list/(?P<list_id>\d+)/reorder_items/$', views.reorder_items, name='reorder_items'),
    url(r'^post_to_twitter/$', views.post_item_to_twitter, name='post_to_twitter'),

    # django-only urls, for development purpose only
    # url(r'^lists/all/$', views.show_lists, name="show_lists"),
    # url(r'^create_list/$', views.create_list, name='create_list'),
    # url(r'^edit_list/(?P<list_id>\d+)/$', views.edit_list, name='edit_list'),
    # url(r'^edit_list/(?P<list_id>\d+)/add_item/$', views.add_item, name='add_item_to_list'),
    # url(r'^edit_list/(?P<list_id>\d+)/delete_item/(?P<item_id>\d+)/$', views.delete_item, name='delete_item_from_list'),
    # url(r'^edit_list/(?P<list_id>\d+)/toggle_done/(?P<item_id>\d+)/$', views.toggle_item_done, name='toggle_item_done'),
    # url(r'^edit_list/(?P<list_id>\d+)/edit_item/(?P<item_id>\d+)/$', views.edit_item, name='edit_item'),
]

SocialTodoList/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),

    url(r'^djangojs/', include('djangojs.urls')),

    url('', include('social_django.urls', namespace='social')),
    url(r'^', include("SocialTodoList.core.urls")),
    url(r'^admin/', admin.site.urls),

    url(r'^.*$', auth_views.login, name="not_found_handler"),
]

SocialTodoList/core/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User


class List(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=200)

    def __str__(self):
        return "{} by {}".format(self.name, self.owner)


class Item(models.Model):
    list = models.ForeignKey(List)
    text = models.CharField(max_length=200)
    order = models.IntegerField(default=0)
    done = models.BooleanField(default=False)
    deadline = models.DateTimeField(null=True)

    def __str__(self):
        return "{} ({})".format(self.text, "done" if self.done else "not done")


class ItemAdmin(admin.ModelAdmin):
    list_display = ('id', 'text', 'list', 'order', 'done', 'deadline')

SocialTodoList/core/views.py
from datetime import datetime
import json

import tweepy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import serializers
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from social_django.models import UserSocialAuth
from tweepy import TweepError

from SocialTodoList import settings
from .models import Item, List


@login_required
def react_index(request):
    lists = List.objects.all()
    payload = {
        "name": request.user.first_name,
        "local_storage": {
            "sessionid": request.COOKIES.get("sessionid"),
            "csrftoken": request.COOKIES.get("csrftoken")
        },
        "lists": lists
    }
    return render(request, "core/react_index.html", payload)


@login_required
def get_all_lists(request):
    user = request.user

    lists = List.objects.filter(owner=user)
    data = serializers.serialize('json', lists)
    return JsonResponse(data, safe=False)


@login_required
def create_new_list(request):
    data = None
    try:
        data = json.loads(request.body.decode())['data']
        name = data.get("newListName")
        if name:
            user = request.user
            user = User.objects.get(username=user.get_username())  # TODO: change to the actual user's ID from request
            new_list = List(name=name, owner=user)
            new_list.save()

            data = serializers.serialize('json', [new_list])
            message = "The list {} was created successfully!".format(new_list.name)
        else:
            raise Exception("Not enough data provided for creating the list.")
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to create the list. Please try again."

    return JsonResponse({"message": message, "newList": data})


@login_required
def delete_list(request, list_id):
    try:
        user = User.objects.get(username=request.user.get_username())
        current_list = List.objects.get(id=list_id)

        if current_list.owner != user:
            raise Exception("Error: The requested list does not belong to the logged in user.")

        current_list.delete()

        message = "The list {} was deleted successfully!".format(current_list.name)
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to delete the list. Please try again."

    return JsonResponse({"message": message})


@login_required
def get_list_info(request, list_id):
    user = User.objects.get(username=request.user.get_username())
    current_list = List.objects.get(id=list_id)

    if current_list and current_list.owner != user:
        raise Exception("Error: The requested list does not belong to the logged in user.")

    items = Item.objects.filter(list__id=list_id).order_by('order')
    data = {
        "items": serializers.serialize('json', items),
        "list": serializers.serialize('json', [current_list])
    }
    return JsonResponse(data, safe=False)


@login_required
def add_item_to_list(request, list_id):
    data = None
    try:
        data = json.loads(request.body.decode())['data']
        text = data.get("newItemText")
        if text:
            user = User.objects.get(username=request.user.get_username())
            current_list = List.objects.get(id=list_id)

            if current_list and current_list.owner != user:
                raise Exception("Error: The requested list does not belong to the logged in user.")

            done = True if data.get("newItemDone") else False
            new_item = Item(list=current_list, text=text, order=0, done=done)
            deadline = data.get("newItemDeadline")
            if deadline:
                new_item.deadline = datetime.strptime(deadline, '%Y-%m-%d')
            new_item.save()

            data = serializers.serialize('json', [new_item])
            message = "The item {} was added successfully!".format(new_item.text)
        else:
            raise Exception("Not enough data provided for creating the item.")
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to add the item. Please try again."

    return JsonResponse({"message": message, "newItem": data})


@login_required
def delete_item_from_list(request, list_id, item_id):
    try:
        user = User.objects.get(username=request.user.get_username())
        current_list = List.objects.get(id=list_id)

        if current_list and current_list.owner != user:
            raise Exception("Error: The requested list does not belong to the logged in user.")

        item = Item.objects.get(id=item_id)
        item.delete()

        message = "The item {} was deleted successfully!".format(item.text)
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to delete the item. Please try again."

    return JsonResponse({"message": message})


@login_required
def toggle_item_done_from_list(request, list_id, item_id):
    data = None
    try:
        user = User.objects.get(username=request.user.get_username())
        current_list = List.objects.get(id=list_id)

        if current_list and current_list.owner != user:
            raise Exception("Error: The requested list does not belong to the logged in user.")

        item = Item.objects.get(id=item_id)
        item.done = True if not item.done else False
        item.save()

        data = serializers.serialize('json', [item])
        message = "The item {} was successfully marked as {}!".format(item.text, "done" if item.done else "not done")
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to edit the item. Please try again."

    return JsonResponse({"message": message, "updatedItem": data})


@login_required
def get_item_info(request, item_id):
    item = Item.objects.get(id=item_id)
    current_list = List.objects.get(id=item.list.id)

    user = User.objects.get(username=request.user.get_username())
    current_list = List.objects.get(id=current_list.id)

    if current_list and current_list.owner != user:
        raise Exception("Error: The requested list does not belong to the logged in user.")

    data = {
        "item": serializers.serialize('json', [item]),
        "list": serializers.serialize('json', [current_list])
    }
    return JsonResponse(data, safe=False)


@login_required
def edit_item_from_list(request, list_id, item_id):
    data = {}
    try:
        data = json.loads(request.body.decode())['data']
        text = data.get("newItemText")
        if text:
            user = User.objects.get(username=request.user.get_username())
            current_list = List.objects.get(id=list_id)

            if current_list and current_list.owner != user:
                raise Exception("Error: The requested list does not belong to the logged in user.")

            done = True if data.get("newItemDone") else False
            deadline = data.get("newItemDeadline")

            item = Item.objects.get(id=item_id)
            item.text = text
            item.done = done
            if deadline:
                item.deadline = datetime.strptime(deadline, '%Y-%m-%d')
            item.save()

            data = {
                "item": serializers.serialize('json', [item]),
                "list": serializers.serialize('json', [current_list])
            }

            message = "The item {} was edited successfully!".format(item.text)
        else:
            raise Exception("Not enough data provided for editing the item.")
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to edit the item. Please try again."

    data["message"] = message
    return JsonResponse(data, safe=False)


@login_required
def reorder_items(request, list_id):
    try:
        data = json.loads(request.body.decode())['data']
        items = data.get("items")
        if items:
            user = User.objects.get(username=request.user.get_username())
            current_list = List.objects.get(id=list_id)

            if current_list and current_list.owner != user:
                raise Exception("Error: The requested list does not belong to the logged in user.")

            for i, item in enumerate(items):
                db_item = Item.objects.get(id=item.get("pk"))
                db_item.order = i
                db_item.save()

            message = "The items were reordered successfully!"
        else:
            raise Exception("Not enough data provided for creating the item.")
    except Exception as e:
        print(":::: ERROR:", e)
        message = "There was an error while trying to reorder the items. Please REFRESH THE PAGE and try again."

    return JsonResponse({"message": message})


@login_required
def post_item_to_twitter(request):
    data = {}
    try:
        data = json.loads(request.body.decode())['data']
        item_id = data.get("itemId")
        list_id = data.get("listId")
        if item_id:
            user = User.objects.get(username=request.user.get_username())
            current_list = List.objects.get(id=list_id)

            if current_list and current_list.owner != user:
                raise Exception("Error: The requested list does not belong to the logged in user.")

            item = Item.objects.get(id=item_id)
            # post to twitter
            user_obj = UserSocialAuth.objects.get(user_id=request.user.id)
            tweepy_handler = generate_tweepy_handler(user_obj.extra_data['access_token']['oauth_token'],
                                                     user_obj.extra_data['access_token']['oauth_token_secret'])

SocialTodoList/core/templates/core/edit_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3><a href="{% url 'core:show_lists' %}">Back to Lists Index</a></h3>
<h3><a href="{% url 'core:edit_list' list.id %}">Back to List "{{ list.name }}"'s Details</a></h3>

<h2>Edit Item from List "{{ list.name }}"</h2>

<div id="editItem">
    <form method="POST" action="{% url 'core:edit_item' list.id item.id %}">
        {% csrf_token %}
        Text: <input type="text" name="newItemText" value="{{ item.text }}" /> <br/>
        Deadline: <input type="date" name="newItemDeadline" value='{{ item.deadline|date:"Y-m-d" }}' /> <br/>
        Done: <input type="checkbox" name="newItemDone" {% if item.done %}checked{% endif %} /> <br/>
        <input type="submit" value="Edit Item"/>
        {% csrf_token %}
    </form>
</div>

{% if messages %}
<h4>Feedback:</h4>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

SocialTodoList/core/templates/core/edit_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit List {{ list.name }}</title>
</head>
<body>
<h3><a href="{% url 'core:show_lists' %}">Back to Lists Index</a></h3>

<h2>Details for list "{{ list.name }}"</h2>
{% if not items %}
<p><i>No items in this list yet.</i></p>
{% endif %}
<ul>
{% for item in items %}
    <li><a {% if item.done %} style="text-decoration:line-through" {% endif %}>{{ item.text }}{% if item.deadline %} (due on {{item.deadline}}){% endif %}</a>
        <a href="{% url 'core:delete_item_from_list' list.id item.id %}">[delete]</a>
        <a href="{% url 'core:toggle_item_done' list.id item.id %}">[mark as {% if item.done %}not done{% else %}done{% endif %}]</a>
        <a href="{% url 'core:edit_item' list.id item.id %}">[edit]</a>
    </li>
{% endfor %}
</ul>

<h3>Add new Item to List</h3>

<div id="addItem">
    <form method="POST" action="{% url 'core:add_item_to_list' list.id %}">
        {% csrf_token %}
        Text: <input type="text" name="newItemText" /> <br/>
        Deadline: <input type="date" name="newItemDeadline" /> <br/>
        Done: <input type="checkbox" name="newItemDone" /> <br/>
        <input type="submit" value="Add Item" />
        {% csrf_token %}
    </form>
</div>

{% if messages %}
<h4>Feedback:</h4>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

SocialTodoList/core/templates/core/react_index.html
{% extends 'base.html' %}
{% load js %}

{% block body %}
<!--<p>Welcome, {{ name }}!</p>-->
<!--<p>JSON String: {{ local_storage }}</p>-->
<!--<p>SessionID: {{ local_storage.sessionid }}</p>-->
<!--<p>CSRF Token: {{ local_storage.csrftoken }}</p>-->
<script type="text/javascript">
  function fillLocalStorage() {
    localStorage.setItem("sessionid", "{{ local_storage.sessionid }}");
    localStorage.setItem("csrftoken", "{{ local_storage.csrftoken }}");
  }

  fillLocalStorage();

</script>

{% if messages %}
  <div style="border: 1px; border-style: dashed; text-align: center;">
    {% for message in messages %}
    <h3{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h3>
    {% endfor %}
  </div>
{% endif %}

<div id="react-app"></div>
{% endblock %}

SocialTodoList/core/templates/core/show_lists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show Lists</title>
</head>
<body>
<h2>Lists Index:</h2>
{% if not lists %}
<p><i>No lists created yet.</i></p>
{% endif %}

<ul>
{% for list in lists %}
    <li><a href="{% url 'core:edit_list' list.id %}">{{ list.name }}</a></li>
{% endfor %}
</ul>

<h3>Create new List</h3>

<div id="addList">
    <form method="POST" action="{% url 'core:create_list' %}">
        {% csrf_token %}
        <input type="text" name="newListName" />
        <input type="submit" value="Create List" />
    </form>
</div>

{% if messages %}
<h4>Feedback:</h4>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</body>
</html>